[package]
name = "q-rs-png"
version = "0.1.0"
authors = ["Perry Birch <perrysd@gmail.com>"]
edition = "2021"

[dependencies]
image = { version = "0.25.2", default-features = false, features = [ "png" ] }
q-rs = { path = "../q-rs" }